name: codeflash.yml
on:

jobs:
  optimize:
    runs-on: ubuntu-latest
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup virtual environment
        uses: ./.github/actions/base-cache
        with:
          python-version: "3.12"
      - name: Install Environment
        run: |
          source .venv/bin/activate
          make install-ci
          pip install codeflash
      - name: ⚡️Codeflash Optimization
        run: codeflash
